<?php

/**
 * @file
 * Contains sell_auto.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sell_auto_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sell_auto module.
    case 'help.page.sell_auto':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module de vente de vehicule en ligne') . '</p>';
      return $output;

    default:
  }
}
  /*
 * implements hook_schema
 *
 * hook destiné à créer une table en base de données
 * dès l'installation du module
 */
function sell_auto_schema() {

  $schema['auto_vehicule'] = array(
    'description' => '',
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Vehicule ID'
      ),
      'marque' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Vehicule marque'
      ),
     'price' => array('type' => 'float', 'not null' => TRUE, 'default' => 0.0),
     'energie' => array('type' => 'varchar','length' => 255,'not null' => TRUE,'default' => '', 'description' => 'Vehicule model'),
      'vitesse' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'id_image' => array('type' => 'int', 'not null' => TRUE),

    ),
    'foreign keys' => array(
      'node_sa_image' => array(
        'table' => 'auto_image',
        'columns' => array('id_image' => 'id'),
       ),
   ),
    'primary key' => array('id')
  );

  $schema['auto_image'] = array(
    'description' => '',
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Vehicule ID'
      ),
      'name' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Image name'
      ),
      'alt' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Image alt'
      ),
      'uuid' => array(
        'type' => 'char',
        'length' => 36,
        'not null' => TRUE,
        'default' => '',
        'description' => 'The Universally Unique Identifier.',
      ),
    ),
    'primary key' => array('id')
  );

  $schema['auto_commande'] = array(
    'description' => 'Commande client',
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Commande ID',
      ),
      'userid' => array(
        'type' => 'int',
        'length' => 10,
        'not null' => TRUE,
        'description' => 'Users ID',
      ),
      'carids' => array(
        'mysql_type' => 'json',
        'description' => 'list of car',
      )
    ),
    'foreign keys' => array(
      'node_sa_user' => array(
        'table' => 'users',
        'columns' => array('uid' => 'uid'),
       ),
   ),
    'primary key' => array('id')
  );

  return $schema;

}
